project:
  type: book

book:
  title: "Github"
  author: "Monika Avila Marquez"
  date: "6/15/2025"
  chapters:
    - index.qmd
    - GitGithub.qmd
    - ConfigurarGit.qmd
    - GitBranches.qmd
    - FileChanges.qmd
    - Commit.qmd
    - PullRequest.qmd
    - MergePullRequest.qmd
    - part: Workflow.qmd
      chapters:   
      - WorkflowWithCommands.qmd
      - BranchingWorkflow.qmd
      - Cloning.qmd
      - Commands.qmd
      - GitRevert.qmd
      - WorkflowCreateGitGithubRepo.qmd
      - WorkflowExistingRepository.qmd
    - ForkClone.qmd
    - GithubProjectManagement.qmd
    - FileReadme.qmd
    - GitHubCopilot.qmd
    - WorkStrategies.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex

# This is highly recommended so GitHub doesn't crash on code chunks
execute:
  freeze: auto